//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.allocations = new HashSet<allocation>();
        }
    
        public int book_id { get; set; }
        [DisplayName("Book-Name")]
        [Required(ErrorMessage ="Enter The Book Name!")]
        [DataType(DataType.Text)]
        [StringLength(30,MinimumLength =5,ErrorMessage ="Enter the name of the book between 5 to 30 characters!")]
        public string book_name { get; set; }
        [DisplayName("Author-Name")]
        [Required(ErrorMessage = "Enter The Author Name!")]
        [DataType(DataType.Text)]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "Enter the name of the Author between 5 to 20 characters!")]
        public string author_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<allocation> allocations { get; set; }
    }
}
