//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Text.RegularExpressions;

    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.allocations = new HashSet<allocation>();
        }
    
        public int student_id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        [DisplayName("Name")]
        [DataType(DataType.Text)]
        [StringLength(20,MinimumLength =5,ErrorMessage ="Enter the name of 5 to 20 characters!")]
        public string name { get; set; }
        [Required(ErrorMessage = "Roll-Number is required")]
        [DisplayName("Roll-No")]
        //[Range(3,8,ErrorMessage ="Give Roll-No between 3 or 8 Digits")]
        
        public string roll_no { get; set; }
        [Required(ErrorMessage = "Email is required")]

        [RegularExpression(@"[a-z0-9]+@[a-z]+\.[a-z]{2,3}", ErrorMessage = "Invalid Email")]
        [DisplayName("E-Mail")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<allocation> allocations { get; set; }
    }
}
